version = 0.1

[default.deploy.parameters]
stack_name = "url-shortener"
resolve_s3 = true
s3_prefix = "url-shortener"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "af-south-1"
